Foreground yes
LocalSocket /tmp/weave-clamd.sock
FixStaleSocket yes
DatabaseDirectory /var/lib/clamav
PidFile /tmp/weave-clamd.pid
LogFile /tmp/weave-clamd.log
MaxThreads 4
StreamMaxLength 20M
MaxScanTime 60000
