import type { CalendarEvent } from "./calendar-model";
import { showPublicFixtures } from "../../config/public-fixtures";

const now = new Date();
const year = now.getFullYear();
const month = now.getMonth();

function at(day: number, hour = 10, minute = 0, monthOffset = 0) {
  return new Date(year, month + monthOffset, day, hour, minute);
}

const calendarFixtureSeeds: CalendarEvent[] = [
  {
    id: "fixture-listening-evening",
    title: "서로의 하루를 듣는 저녁",
    summary: "일과 관계 사이에서 요즘 마음에 남은 질문을 천천히 나누는 모임",
    description: "정답을 찾기보다 서로의 이야기를 충분히 듣습니다. 원불교가 처음이어도 편하게 참여할 수 있어요.",
    organizerName: "서울 청년회",
    startAt: at(6, 19, 30),
    endAt: at(6, 21, 0),
    allDay: false,
    timeZone: "Asia/Seoul",
    topic: "나와 마음",
    region: "서울",
    locationName: "원남교당 청년 공간",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=960&q=82",
      alt: "햇살 아래 둘러앉아 이야기를 나누는 청년들",
      width: 960,
      height: 640,
    },
    gallery: [
      {
        url: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=82",
        alt: "편안한 자리에서 대화를 이어가는 모임",
        width: 1200,
        height: 800,
      },
    ],
    visibility: "public",
    registrationStatus: "open",
    registrationDeadline: at(5, 23, 59),
    eventState: "confirmed",
    sourceType: "manual",
    origin: "fixture",
  },
  {
    id: "fixture-local-service",
    title: "우리 동네 한 끼 나눔",
    summary: "장보기부터 식사 준비까지 이웃과 함께 만드는 작은 봉공 활동",
    description: "처음 참여하는 사람도 현장에서 역할을 고를 수 있습니다. 편한 옷차림으로 오세요.",
    organizerName: "대전충남교구 청년회",
    startAt: at(11, 10),
    endAt: at(11, 15),
    allDay: false,
    timeZone: "Asia/Seoul",
    topic: "사회와 실천",
    region: "대전",
    locationName: "대전역 인근 공유 부엌",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=960&q=82",
      alt: "함께 준비한 음식을 이웃과 나누는 활동",
      width: 960,
      height: 640,
    },
    visibility: "public",
    registrationStatus: "open",
    registrationDeadline: at(9, 23, 59),
    eventState: "confirmed",
    sourceType: "manual",
    origin: "fixture",
  },
  {
    id: "fixture-career-table",
    title: "선배의 일터를 묻는 테이블",
    summary: "직업 소개보다 일하는 마음과 선택의 순간을 듣는 작은 대화 자리",
    description: "서로 다른 분야에서 일하는 선배 세 명과 둥근 테이블에 앉아 질문을 나눕니다.",
    organizerName: "경기인천교구 청년회",
    startAt: at(16, 14),
    endAt: at(16, 17),
    allDay: false,
    timeZone: "Asia/Seoul",
    topic: "일과 진로",
    region: "경기",
    locationName: "수원 청년공간",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=960&q=82",
      alt: "테이블에 둘러앉아 일과 삶을 이야기하는 사람들",
      width: 960,
      height: 640,
    },
    visibility: "public",
    registrationStatus: "closing_soon",
    registrationDeadline: at(15, 18),
    eventState: "tentative",
    sourceType: "google",
    origin: "fixture",
  },
  {
    id: "fixture-study-camp",
    title: "여름 마음공부 한마당",
    summary: "생활 속 마음공부를 함께 익히고 쉬어 가는 하루",
    description: "짧은 공부와 산책, 모둠 대화를 번갈아 진행합니다. 세부 일정은 신청자에게 안내해 드려요.",
    organizerName: "원불교 청년회",
    startAt: at(20, 0),
    endAt: at(21, 0),
    allDay: true,
    timeZone: "Asia/Seoul",
    topic: "배움과 신앙",
    region: "전국",
    locationName: "서울회관",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=960&q=82",
      alt: "한자리에 모여 환하게 웃는 청년들",
      width: 960,
      height: 640,
    },
    visibility: "public",
    registrationStatus: "closed",
    registrationDeadline: at(17, 23, 59),
    eventState: "confirmed",
    sourceType: "ics",
    origin: "fixture",
  },
  {
    id: "fixture-climate-walk",
    title: "기후를 생각하는 밤 산책",
    summary: "도시의 여름을 걸으며 일상에서 바꿀 수 있는 선택을 찾아보는 시간",
    description: "한 시간 정도 천천히 걷습니다. 비가 오면 같은 시각 온라인 대화로 바뀝니다.",
    organizerName: "청년 실천팀",
    startAt: at(24, 19),
    endAt: at(24, 20, 30),
    allDay: false,
    timeZone: "Asia/Seoul",
    topic: "사회와 실천",
    region: "부산",
    locationName: "수영강 시민공원",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=960&q=82",
      alt: "저녁빛이 남은 공원을 함께 걷는 산책",
      width: 960,
      height: 640,
    },
    visibility: "public",
    registrationStatus: "not_required",
    eventState: "confirmed",
    sourceType: "timetree_link",
    origin: "fixture",
  },
  {
    id: "fixture-welcome-workshop",
    title: "처음 온 사람을 맞이하는 법",
    summary: "낯선 사람이 혼자 남지 않도록 초대와 환대의 동선을 함께 만드는 워크숍",
    description: "실제 행사 장면을 떠올리며 안내 문구와 역할표를 만들어 봅니다.",
    organizerName: "광주전남교구 청년회",
    startAt: at(28, 13),
    endAt: at(28, 16),
    allDay: false,
    timeZone: "Asia/Seoul",
    topic: "관계와 공동체",
    region: "광주",
    locationName: "광주교당 소법당",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=960&q=82",
      alt: "작은 모둠으로 둘러앉아 환대 방법을 정리하는 모습",
      width: 960,
      height: 640,
    },
    visibility: "member_only",
    registrationStatus: "open",
    registrationDeadline: at(26, 23, 59),
    eventState: "confirmed",
    sourceType: "manual",
    origin: "fixture",
  },
  {
    id: "fixture-next-study",
    title: "일상에서 시작하는 7일 공부",
    summary: "하루 한 번 마음을 살피는 방법을 익히고 서로의 기록을 나누는 모임",
    description: "첫날 함께 방법을 익힌 뒤 일주일 동안 각자의 자리에서 실천합니다.",
    organizerName: "온라인 공부 모임",
    startAt: at(4, 20, 0, 1),
    endAt: at(4, 21, 30, 1),
    allDay: false,
    timeZone: "Asia/Seoul",
    topic: "배움과 신앙",
    region: "온라인",
    locationName: "온라인",
    thumbnail: {
      url: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=960&q=82",
      alt: "노트와 따뜻한 음료를 두고 공부를 준비한 책상",
      width: 960,
      height: 640,
    },
    visibility: "public",
    registrationStatus: "open",
    registrationDeadline: at(3, 20, 0, 1),
    eventState: "confirmed",
    sourceType: "google",
    origin: "fixture",
  },
];

export const calendarFixtures: CalendarEvent[] = showPublicFixtures
  ? calendarFixtureSeeds
  : [];

export function getCalendarFixture(eventId: string) {
  return calendarFixtures.find((event) => event.id === eventId);
}
