async (rootPage) => {
  const page=await rootPage.context().newPage();const base='http://127.0.0.1:4193';const results=[];
  const check=(name,ok,detail)=>{results.push({name,status:ok?'PASS':'FAIL',detail});if(!ok)throw new Error(name+' '+JSON.stringify(detail));};
  await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.goto(base+'/calendar/new');
  await page.evaluate(()=>{const s=window.__weaveTest;s.callableResponses={...s.callableResponses,createManualEvent:input=>{s.eventExtras={...input,startAt:new Date(input.startAt),endAt:new Date(input.endAt)};return {eventId:'synthetic-event-0',status:'published'};}};});
  await page.getByLabel('행사 이름 (필수)',{exact:true}).fill('합성 새 행사');
  await page.getByLabel('주최 (필수)',{exact:true}).fill('합성 주최');
  await page.getByLabel('지역 (필수)',{exact:true}).fill('서울');
  await page.getByLabel('시작 (필수)',{exact:true}).fill('2026-10-10T10:00');
  await page.getByLabel('종료 (필수)',{exact:true}).fill('2026-10-10T12:00');
  await page.getByLabel(/장소 이름/).fill('합성 장소');
  await page.locator('.event-editor-step-visibility select').selectOption('public');
  await page.getByRole('button',{name:'행사 등록하기',exact:true}).click();
  await page.getByRole('heading',{name:'행사를 저장했어요',exact:true}).waitFor();
  check('event completion removes create form',await page.locator('.event-editor-form').count()===0);
  check('event completion focus',await page.getByRole('status').filter({has:page.getByRole('heading',{name:'행사를 저장했어요'})}).evaluate(el=>el===document.activeElement));
  check('event three next actions',await page.getByRole('link',{name:'저장한 행사 보기'}).count()===1&&await page.getByRole('link',{name:'내 행사 관리',exact:true}).count()===1&&await page.getByRole('link',{name:'행사 일정으로 돌아가기',exact:true}).count()===1);
  await page.getByRole('link',{name:'저장한 행사 보기'}).click();await page.getByRole('heading',{name:'합성 새 행사',level:1}).waitFor();check('saved event opens returned ID',page.url().includes('/events/synthetic-event-0'));
  await page.goto(base+'/activities/career-visit');
  check('example activity detail marked',await page.getByText(/사용 예시.*실제 활동 기록/).first().isVisible());
  check('example activity no owner tools',await page.locator('.owner-icon-action').count()===0);
  check('example material no download',await page.getByRole('button',{name:'다운로드',exact:true}).count()===0);
  await page.evaluate(()=>{window.__weaveTest.activities=[{id:'synthetic-published',slug:'synthetic-published',title:'합성 실제 활동',topic:'나와 마음',type:'모임',status:'published',visibility:'public',summary:'합성 검증용',story:'합성 본문',date:'2026-09-30',place:'서울'}];});
  await page.getByRole('navigation',{name:'주요 메뉴'}).getByRole('link',{name:'활동 기록',exact:true}).click();
  const actualCard=page.locator('.activity-card').filter({has:page.getByRole('heading',{name:'합성 실제 활동',exact:true})});
  await actualCard.waitFor();check('published activity no example label',await actualCard.getByText(/사용 예시/).count()===0);
  await actualCard.getByRole('heading',{name:'합성 실제 활동',exact:true}).getByRole('link').click();
  await page.getByRole('heading',{name:'합성 실제 활동',level:1}).waitFor();check('published detail no example banner',await page.locator('main').getByText(/사용 예시.*실제 활동 기록/).count()===0);
  await page.goto(base+'/resources');
  await page.locator('summary').filter({hasText:'불러온 자료의 형식 분포'}).click();
  await page.getByRole('img',{name:/현재 불러온 실제 자료/}).waitFor();
  await page.addScriptTag({url:base+'/node_modules/axe-core/axe.min.js'});
  const chartAxe=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}}));
  check('expanded chart axe',chartAxe.violations.length===0,chartAxe.violations.map(x=>x.id));
  const chart=await page.locator('.recharts-bar-rectangle').count();check('reduced motion chart rendered',chart>0,chart);
  await page.close();return {synthetic:true,results};
}
